- name: Upgrade to last update in remote repo
  hosts: webservers
  remote_user: takosuke
  vars:
  - app_name: nemesis-airbrush
  - deploy_user: takosuke
  - repo_path: "takosuke/nemesis-airbrush"
  - repo_remote : origin
  - repo_version: master
  - webapps_dir: "/home/takosuke/public_html"


  roles:
  - update_repo
