- name: Initial deployment of pizzasuicideclub.com
  hosts: webservers
  remote_user: takosuke
  vars:
  - app_name: nemesis-airbrush
  - deploy_user: takosuke
  - domain_name: nemesis-airbrush.pizzasuicideclub.com
  - repo_path: "takosuke/nemesis-airbrush"
  - repo_remote : origin
  - repo_version: master
  - webapps_dir: "/home/takosuke/public_html"
  - app_root: "html"
  - static_root: "static"
  - wsgi_callable: app
  - cronjob_script: "image_scripts.py"

#  vars_prompt:
  roles:
  - clone_repo
  - log_setup
  - nginx_setup
  - supervisord_setup
  - py3_virtualenv_setup
  - pip_requirements
  - app_setup
  - cronjob_setup
  - install_bower_dependencies
